Gemfile.lock, app/models/place.rb, db/migrate/20200224142844_create_places.rb, db/schema.rb, test/models/place_test.rb
=> model place done

Gemfile.lock, app/models/place_genre.rb, db/migrate/20200224144850_create_place_genres.rb, db/schema.rb, test/models/place_genre_test.rb
création du place_genres model. !
=> Placegenre model

app/views/layouts/application.html.erb, config/meta.yml
Added the meta tags in the HTML and removed some useless ones from meta.yml
=> fixed meta tags

Gemfile, Gemfile.lock, db/migrate/20200225135503_change_type_to_category_in_places.rb, db/places.json, db/schema.rb, db/seeds.rb
Places instead of Bars
No Bookings
No Reviews
Avatar present on most users but not all (25% missing approx.)
Places only have one picture for now, because we'll probably have to seed again a lot of times in the next 2 weeks
=> Working seeds

app/assets/stylesheets/components/_bottom_navbar.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search-card.scss, app/assets/stylesheets/components/_tag.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_index.scss, app/views/components/_search-card.html.erb, app/views/components/_tag.html.erb, app/views/layouts/application.html.erb, app/views/places/index.html.erb
J'ai fait :
- le design global de la page INDEX/Places
-> il reste bien sur des petites modifs de CSS à faire (des couleurs à changer etc mais au global c'est là).
- le design des tags par style de musique, qui nous serviront dès qu'on sera connecté à l'API Spotify. Idem il y aura surement des class/id à rajouter en fonction de comment est la data spotify.
=> Index places

app/assets/stylesheets/components/_back_arrow.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_colors.scss, app/views/components/_back_arrow.html.erb, app/views/places/index.html.erb, app/views/places/show.html.erb
We'll review (variable) position when we refacto the index page as it is not looking well on the index.
=> Previous button

app/models/genre.rb, lib/tasks/genre.rake
- data gotten from Spotify.
- TODO: Make it automatic through API
- seeding through `rails genre:seed`
=> Adding a seed for genres

app/javascript/controllers/fade_toast_controller.js, app/views/components/_flashes.html.erb
=> 3 sec auto disappearance toasters

app/assets/stylesheets/components/_background_logo.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
=> Home page revamped according to new design

app/assets/stylesheets/components/_horizontal_scroll.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/views/components/_horizontal_scroll.html.erb, app/views/pages/home.html.erb
=> Horizontal-scrolling component + example on home screen

app/assets/stylesheets/pages/_tastes.scss, app/controllers/user_genres_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/tastes.js, app/policies/user_genre_policy.rb, app/views/pages/tastes.html.erb, config/routes.rb, config/webpack/environment.js, package.json, test/controllers/user_genres_controller_test.rb, test/policies/user_genre_policy_test.rb, yarn.lock
- Sticky header on /tastes screen
- Better CSS
- Clicking Tags now creates / destroys `user_genres`
=> Select Initial Tags complete

app/models/genre.rb, app/models/sub_genre.rb, db/migrate/20200227173951_create_sub_genres.rb, db/migrate/20200227183627_add_genre_to_sub_genres.rb, db/schema.rb, lib/tasks/genre.rake, test/models/sub_genre_test.rb
You can seed the sub_genres table with the command:
`rails genre:sub_seed`
- `rap` is renamed `hip-hop` before matching
- `hip hop` is renamed `hip-hop` before matching
- `&` is changed to `-n-` before matching
Everything works :)
=> Create sub genres

app/assets/stylesheets/components/_place_card.scss, app/assets/stylesheets/pages/_home.scss, app/views/components/_place_card.html.erb, app/views/pages/home.html.erb
=> Finished carrousels and links

app/javascript/controllers/signin_feedback_controller.js, app/models/sub_genre.rb, app/views/devise/sessions/_new.html.erb
We now suggest only 5 artists
+ nice little message saying we fetch the data when you sign in.
=> Only top 5 artists and message at signin

app/assets/stylesheets/components/_search-card.scss, app/views/components/_search-card.html.erb
Juste debug des photos qui changeaient de taille entre certaines pages
=> debug photo sur les cards

app/assets/stylesheets/components/_horizontal_scroll.scss, app/assets/stylesheets/components/_place_card.scss, app/assets/stylesheets/components/_search_bar.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Changements sur la tailles des cartes selection of bars
search remontée
modifications polices
img cover fit
=> Css homepage

app/assets/stylesheets/pages/_places_index.scss, app/views/components/_search_bar.html.erb, app/views/places/index.html.erb
=> Search bar added on index. It keeps the last search.

`, app/assets/stylesheets/components/_place_card.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/controllers/places_controller.rb, app/models/artist.rb, app/models/place.rb, app/views/components/_place_card.html.erb, app/views/pages/home.html.erb, app/views/places/index.html.erb, db/seeds.rb
- Bars above shows only bars with the same genres as the user
- The artist section should show artists that are favored by the user. (Fallback to a seeded list if the Spotify profile is not completed)
- Around me shows only bars near the user
=> Home - Nearby Section / Artists logic implemented

app/assets/stylesheets/pages/_places_index.scss
=> Links are no longer outlined on the index page

app/models/sub_genre.rb, app/models/user_artist.rb, app/models/user_artist_genre.rb, db/migrate/20200302114721_remove_name_from_user_artist_genre.rb, db/migrate/20200302114803_add_sub_genre_to_user_artist_genre.rb, db/schema.rb
Instead of stocking the sub_genre name in user_artists_genre, we stock the sub_genre itself
=> User Artist Genre is connected to Sub Genres

app/assets/stylesheets/pages/likes_index.scss, app/views/likes/index.html.erb
=> coeur ajouté sur le title spots <3

app/assets/stylesheets/components/_horizontal_scroll.scss
!!! A tester en local avant de merger !!!
=> Now we can scroll vertically while being on the horizontal carrousels

app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_places_index.scss, app/assets/stylesheets/pages/_tastes.scss, app/views/pages/tastes.html.erb
Logo not cropped anymore on tastes
Tastes headers are scrollable
Better dropdown on genres
Scroll on home fixed
=> Better front everywhere

app/assets/stylesheets/components/_place_card.scss, app/assets/stylesheets/components/_search_bar.scss, app/assets/stylesheets/pages/_home.scss
=> Home front

app/assets/stylesheets/components/_dropdown_menu.scss, config/initializers/devise.rb
Sign out via Get
Link is not blue
=> Fixed Sign Out

app/assets/stylesheets/pages/_places_index.scss, app/javascript/controllers/tab_selection_index_controller.js, app/views/places/index.html.erb
* Genres Search Bar is now clean: https://share.getcloudapp.com/JruWgZZP
* We store the genres tab preference in your local storage but not if you come for an address
=> Iso search bar

app/controllers/likes_controller.rb
fix bug pour faire apparaitre que les like du current user (je peux pas test en local)
=> only current user likes

app/views/places/show.html.erb
Le calcul des étoiles n'était pas bon sur la show d'une place
=> rating in show repaired

app/controllers/likes_controller.rb, app/javascript/controllers/likes_controller.js, app/views/places/show.html.erb, config/routes.rb
=> Firing hidden forms with no reload for likes

app/controllers/pages_controller.rb, app/javascript/controllers/places_search_controller.js, app/views/components/_search_bar_home.html.erb, config/routes.rb
La geolocation fonctionne mais peut être un peu lente, à tester sur heroku et voir si ca bug pas
=> geoloc set up

app/javascript/controllers/select2search_controller.js, app/views/components/_search_bar_home.html.erb, app/views/places/_search_by_genres_tab.html.erb, app/views/places/_search_by_location_tab.html.erb, app/views/places/index.html.erb
Now seperated in different partials, the search bar looks like the
others when we select a search by genre.
If a genre is selected, the icon disappears to let some space.
=> places#index refactorings + search bar for genres

app/views/components/_back_arrow.html.erb, app/views/places/index.html.erb, app/views/places/show.html.erb
Now goes back to the real back history.
=> Clever back button

app/controllers/pages_controller.rb, app/controllers/places_controller.rb, app/javascript/controllers/map_controller.js, app/views/layouts/application.html.erb, app/views/places/_search_by_location_tab.html.erb
- Now the map goes to the query address
- Now the map goes to the Event's location by default
- Now the map zooms enough around the said location
- Now the map can show any place in the world
=> Fix map issues

app/assets/stylesheets/pages/loading.scss
=> animation au dessus du titre GetOut

app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_search-card.scss, app/views/components/_search-card.html.erb
J'ai rendu plus joli les pop up sur la MAP
et j'ai normalement résolu le problème des images sur les places cards qui changeaient de format
Je rererevérifierai en prod après le push
=> Bug fix css

app/assets/stylesheets/pages/_show.scss, app/views/places/show.html.erb
=> Place Show CSS

app/assets/stylesheets/components/_search-card.scss, app/assets/stylesheets/components/_search_bar.scss, app/assets/stylesheets/pages/_places_index.scss, app/javascript/controllers/select2search_controller.js
- Tons of small front fixes as I explained IRL
- Search by Genres dropdown
=> Place Index & Search by genres refacto

app/assets/stylesheets/components/_search_bar.scss, app/javascript/controllers/select2search_controller.js, app/views/places/_search_by_genres_tab.html.erb
The placeholder leaves when you add a genre
https://share.getcloudapp.com/v1urND2b
=> Placeholder

app/assets/stylesheets/components/_likes_card.scss, app/assets/stylesheets/pages/_likes_index.scss, app/views/likes/index.html.erb
- Fix sur la taille des cards checked et non checked
- Le bouton "Clear X" a été remonté et remplacé par "All places" suivi du nombre de likes
- Fix sur la transition au moment de l'ouverture des filtres sur les cards
**Amelioration**
- Lorsqu'on clique sur all places, la page se recharge
=> modifications on filters and cards
